version: "3"
services:
  php:
    build:
        context: .
        dockerfile: ./docker/php/Dockerfile
    volumes:
      - "./app:/var/www/app"
      # confファイルを書き換える場合は/etc/mysql/conf.d配下に設定ファイルをvolume
      # - "./my/custom:/etc/mysql/conf.d"
    ports:
      - "${PHP_PORT}:8000"
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    volumes:
      - "./docker/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./docker/nginx/conf.d:/etc/nginx/conf.d"
    ports:
      - "${NGINX_PORT}:80"
  mysql:
    image: "mysql:5.7"
    volumes:
      - "./docker/mysql/var/log/mysql:/var/lib/mysql:delegated"
      # confファイルを書き換える場合は/etc/mysql/conf.d配下に設定ファイルをvolume
      # - "./my/custom:/etc/mysql/conf.d"
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=openwrok
      - MYSQL_DATABASE=openwrok
      - MYSQL_USER=openwrok
      - MYSQL_PASSWORD=openwrok
